import { Links } from './links.model';
import { Owner } from './owner.model';
import { Namespace } from './namespace.model';
import { Permissions } from './permissions.model';

export interface Project {
  id: number;
  description: string;
  name: string;
  name_with_namespace: string;
  path: string;
  path_with_namespace: string;
  created_at: string;
  default_branch: null | string;
  tag_list: any[];
  ssh_url_to_repo: string;
  http_url_to_repo: string;
  web_url: string;
  readme_url: null | string;
  avatar_url: null;
  star_count: number;
  forks_count: number;
  last_activity_at: string;
  namespace: Namespace;
  _links: Links;
  archived: boolean;
  visibility: string;
  resolve_outdated_diff_discussions: null;
  container_registry_enabled: boolean;
  issues_enabled: boolean;
  merge_requests_enabled: boolean;
  wiki_enabled: boolean;
  jobs_enabled: boolean;
  snippets_enabled: boolean;
  shared_runners_enabled: boolean;
  lfs_enabled: boolean;
  creator_id: number;
  import_status: string;
  open_issues_count: number;
  public_jobs: boolean;
  ci_config_path: null;
  shared_with_groups: any[];
  only_allow_merge_if_pipeline_succeeds: boolean;
  request_access_enabled: boolean;
  only_allow_merge_if_all_discussions_are_resolved: boolean;
  printing_merge_request_link_enabled: boolean;
  merge_method: string;
  permissions: Permissions;
  approvals_before_merge: number;
  mirror: boolean;
  owner?: Owner;
}